version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-seed:/docker-entrypoint-initdb.d
    command: mongod --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - spark-network
    restart: unless-stopped

  mongo-seed:
    build: ./mongo-seed
    volumes:
      - ./mongo-seed:/data/seed
    depends_on:
      - mongo
    networks:
      - spark-network

  spark:
    build: ./spark/
    container_name: spark
    ports:
      - "8888:8888"
      - "4040-4049:4040-4049"
    volumes:
      - ./notebooks:/usr/local/spark/notebooks
    networks:
      - spark-network
    depends_on:
      - mongo

networks:
  spark-network:
